# Create here the Drupal site you would like
version: '2'
services:
  drupal:
    # Choose your URL and hostname for this Docker Container
    # NEEDS to end with '.docker.amazee.io' !
    # DO NOT remove the '&hostname'
    hostname: &hostname changeme.net.docker.amazee.io

    environment:
      # If you like to have php with xdebug running, uncomment this:
      #XDEBUG: "true"

      # If you would like to use blackfire.io, uncomment and add your server credentials:
      #BLACKFIRE_SERVER_ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      #BLACKFIRE_SERVER_TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx



################################################
### Do not change anything below here, unless you know what you do
      VIRTUAL_HOST: *hostname
    image: amazeeio/drupal:php70-basic
    volumes:
      - .:/var/www/drupal/public_html
    volumes_from:
      - container:ssh-agent
    container_name: *hostname
    network_mode: "bridge"
    ports:
      - "3306"
